name: dem-stitcher-isce
channels:
 - conda-forge
 - anaconda
 - defaults
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python>=3.8,<3.10
 - pip
 - affine>=2.3.0
 - asf_search>=3.0.4
 - boto3
 - dateparser
 - Fiona>=1.8.6
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - gdal>=3,<3.4
 - geopandas>=0.5.1
 - hyp3lib>=1.7
 - ipykernel
 - isce2
 - jinja2
 - joblib
 - jsonschema==3.2.0
 - jupyter
 - lxml
 - matplotlib
 - netcdf4
 - notebook
 - numpy
 - numpy>=1.17.2
 - pandas>=0.25.1
 - papermill
 - proj>=8.0,<9.0
 - pytest
 - pytest-cov
 - rasterio>=1.2
 - setuptools
 - setuptools_scm
 - Shapely>=1.6.4
 - tqdm>=4.32.2