name: dem-stitcher-310
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python=3.10
 - pip
 - pip:
    - affine>=2.3.0
    - Fiona>=1.8.6
    - geopandas>=0.5.1
    - numpy>=1.17.2
    - pandas>=0.25.1
    - rasterio==1.3a3
    - Shapely>=1.6.4
    - matplotlib
    - tqdm>=4.32.2
    - notebook
    - requests
    - boto3
    - setuptools
    - setuptools_scm
    - wheel
    - pytest
    # for testing and distribution
    - flake8-blind-except
    - flake8-builtins
    - flake8-import-order
    - pytest
    - setuptools
    - setuptools_scm
    - wheel
