name: Run Pytest
description: Composite for pytest

runs:
  using: "composite"
  steps:
    - name: Install dependencies, linter, pytest
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install flake8 pytest
        python -m pip install .
    - name: Lint with flake8
      shell: bash
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 .
    - name: run pytest
      shell: bash
      run: |
        pytest tests