name: Run Pytest
description: Composite for pytest

runs:
  using: "composite"
  steps:
    - uses: extractions/netrc@v1
      with:
          machine: urs.earthdata.nasa.gov
          username: ${{ secrets.EARTHDATA_USERNAME }}
          password: ${{ secrets.EARTHDATA_PASSWORD }}
    - name: Install dependencies, linter, papermill and kernel for tests
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install flake8 pytest papermill
        python -m pip install .
        python -m ipykernel install --user --name dem_stitcher
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 .
    - name: run pytest
      run: |
        pytest tests