name: Run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - uses: extractions/netrc@v1
      with:
          machine: urs.earthdata.nasa.gov
          username: ${{ secrets.EARTHDATA_USERNAME }}
          password: ${{ secrets.EARTHDATA_PASSWORD }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install -r requirements.txt
        python -m pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 .
    - name: run pytest
      run: |
        pytest tests