name: Pytest

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["py310", "py311", "py312", "py313", "default"]  # `default` is python 3.14
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: extractions/netrc@v3
        with:
          machine: urs.earthdata.nasa.gov
          username: ${{ secrets.EARTHDATA_USERNAME }}
          password: ${{ secrets.EARTHDATA_PASSWORD }}

      - uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: latest
          environments: ${{ matrix.environment }}

      - name: Pytest in pixi environment
        run: pixi run -e ${{ matrix.environment }} pytest . -m 'not notebook'
